# Copyright 2025 KMEE
# License LGPL-3.0 or later (https://www.gnu.org/licenses/LGPL).

{
    "name": "Express Sign Shop",
    "version": "17.0.1.0.0",
    "license": "LGPL-3",
    "author": "KMEE",
    "website": "https://kmee.com.br",
    "depends": [
        "connector_elasticsearch",
        "fastapi",
        "sale_channel_search_engine_category",
        "sale_channel_search_engine_product",
        "shopinvader_anonymous_partner",
        #
        "shopinvader_api_address",
        "shopinvader_api_cart",
        "shopinvader_api_cart_step",
        "shopinvader_api_customer",
        "shopinvader_api_lead",
        "shopinvader_api_sale",
        "shopinvader_api_sale_loyalty",
        "shopinvader_api_settings",
        "shopinvader_api_wishlist",
        #
        "shopinvader_api_delivery_carrier",
        #
        "shopinvader_api_payment_cart",
        "shopinvader_api_payment_provider_custom",
        "shopinvader_api_payment_provider_sips",
        "shopinvader_api_payment_provider_stripe",
        #
        "shopinvader_api_signin_jwt",
        #
        "shopinvader_fastapi_auth_jwt",
        #
        "shopinvader_product_brand_tag",
        "shopinvader_product_brand",
        "shopinvader_product_description",
        "shopinvader_product_seo",
        "shopinvader_product_url",
        "shopinvader_product",
        "shopinvader_search_engine_image",
        "shopinvader_search_engine_product_brand_image",
        "shopinvader_search_engine_product_price",
        "shopinvader_search_engine_product_stock_state",
        "shopinvader_search_engine_update_image",
        "shopinvader_search_engine_update_product_brand_image",
        "shopinvader_search_engine_update_product_brand",
        "shopinvader_search_engine_update_product_media",
        "shopinvader_search_engine_update_product_template_multi_link",
        # "shopinvader_partner",
        # "shopinvader_search_engine_partner",
        # "shopinvader_partner_url",
        # "sale_channel_search_engine_reseller",
        "shopinvader_search_engine",
        # "shopinvader_api_sale_substate",
        # "shopinvader_product_attribute_set",
        # "shopinvader_product_template",
        # "shopinvader_search_engine_product_template",
    ],
    "external_dependencies": {"python": ["fastapi", "pydantic", "extendable_pydantic"]},
    "data": [
        # "views/fastapi_endpoint.xml",
        # "data/res_users.xml",
        # "data/res_groups.xml",
        # "data/auth_jwt_validator.xml",
        # "data/fastapi_endpoint.xml",
        # "data/se_backend.xml",
        # "data/se_index_config.xml",
        # "data/se_index.xml",
        # "data/se_thumbnail_size.xml",
        # "data/se_image_field_thumbnail_size.xml",
        # "data/fs_storage.xml",
        # "data/sale_channel.xml",
    ],
    "demo": [
    ],
}
